### PR TITLE
updated BepInEx payload (5.4.21)

### PR DESCRIPTION
**Pull request by SpikeHimself**
updated BepInEx payload (5.4.21)

I've tried to keep the BepInEx.cfg intact where possible. The only thing I changed was `WriteUnityLog` under `[Logging.Disk]`, which is now `true`, as I believe this is valuable for mod authors receiving bug reports.

### CODE REVIEW

**Comment by SpikeHimself** [comment]
Thanks for accepting my PR @TanninOne! What's the ETA for release? Is there anything else I can do?

**Comment by Pickysaurus** [comment]
It will be pushed out to users later today: https://www.nexusmods.com/site/mods/210?tab=files

**Comment by SpikeHimself** [comment]
Awesome, thank you very much!

**Comment by TanninOne** [comment]
@SpikeHimself Thank you for the contribution!
I took the opportunity to clean up the repo and build system a bit. This shouldn't affect functionality at all, but please do let me know if there's any new issues with this build.

**Pull request merged**
